script_key = "oTALnmFjjSIMCVuwrMGmmyGerIskdYJT"
getgenv().GAG2 = {
	Optimization = true,
	Debug = true,
	Fps = 10,
	AutoBuySeed = true,
	["seed dont buy"] = {
		"Strawberry",
		"Blueberry",
		"Tulip",
		"Tomato",
		"Apple",
	},
	BuyGearShop = {
		"Common Sprinkler",
		"Uncommon Sprinkler",
		"Common Watering Can",
		"Super Sprinkler",
		"Super Watering Can",
	},
	BuyGearMinSheckles = 500000,
	PlantSeeds = {
		["Carrot"] = 0,
		["Gold"] = 10000,
		["Rainbow"] = 10000,
		["Strawberry"] = 0,
		["Blueberry"] = 0,
		["Tomato"] = 0,
		["Apple"] = 0,
		["Bamboo"] = 300,
		["Corn"] = 200,
		["Cactus"] = 200,
		["Pineapple"] = 200,
		["Mushroom"] = 300,
		["Green Bean"] = 200,
		["Banana"] = 200,
		["Grape"] = 200,
		["Coconut"] = 200,
		["Mango"] = 200,
		["Rocket Pop"] = 300,
		["Dragon Fruit"] = 200,
		["Acorn"] = 200,
		["Cherry"] = 200,
		["Sunflower"] = 200,
		["Fire Fern"] = 200,
		["Venus Fly Trap"] = 200,
		["Pomegranate"] = 200,
		["Poison Apple"] = 200,
		["Venom Spitter"] = 200,
		["Briar Rose"] = 200,
		["Romanesco"] = 200,
		["Ghost Pepper"] = 200,
		["Moon Bloom"] = 200,
		["Hypno Bloom"] = 200,
		["Dragon's Breath"] = 200,
	},
	DestroyPlants = {
		"Strawberry",
		"Blueberry",
		"Tomato",
		"Apple",
	},

	BuyPets = {
		["Bunny"] = 6,
		["Unicorn"] = 6,
		["Raccoon"] = 999,
		["Bald Eagle"] = 999,
	},
	EquipPets = {
		["Unicorn"] = { Priority = 1 },
		["Bunny"] = { Priority = 2 },
	},
	SellPets = {
		"Frog",
		"Owl",
		"Turtle",
		"Bee",
	},
	UseWateringCans = { "Common Watering Can" },
	UseSprinklers = {
		"Common Sprinkler",
		"Uncommon Sprinkler",
		"Rare Sprinkler",
		"Legendary Sprinkler",
	},
	CollectSeedPacks = true,
	COLLECT_PLANT_IF_MUTATED = { "Mushroom", "Rocket Pop" },
	SellFruitMultiplier = {
		["Rocket Pop"] = 1,
		["Bamboo"] = 1,
		["Mushroom"] = 1,
	},
	BuyAuction = {},
	SeedInventoryLimit = {
		["Carrot"] = 9999999,
		["Strawberry"] = 0,
		["Blueberry"] = 0,
		["Tulip"] = 0,
		["Tomato"] = 0,
		["Apple"] = 0,
		["Bamboo"] = 300,
		["Corn"] = 2,
		["Cactus"] = 2,
		["Pineapple"] = 2,
		["Mushroom"] = 300,
		["Green Bean"] = 2,
		["Banana"] = 2,
		["Grape"] = 2,
		["Coconut"] = 2,
		["Mango"] = 2,
		["Rocket Pop"] = 300,
		["Dragon Fruit"] = 2,
		["Acorn"] = 2,
		["Cherry"] = 2,
		["Sunflower"] = 2,
		["Fire Fern"] = 2,
		["Venus Fly Trap"] = 10,
		["Pomegranate"] = 10,
		["Poison Apple"] = 10,
		["Venom Spitter"] = 10,
		["Briar Rose"] = 10,
		["Romanesco"] = 10,
		["Ghost Pepper"] = 10,
		["Moon Bloom"] = 100,
		["Hypno Bloom"] = 100,
		["Dragon's Breath"] = 100,
	},
	GearInventoryLimit = {
		["Common Sprinkler"] = 100,
		["Uncommon Sprinkler"] = 100,
		["Common Watering Can"] = 100,
		["Rare Sprinkler"] = 100,
		["Legendary Sprinkler"] = 100,
	},
	DestroyUntilMinPlants = 600,
	LimitPlants = 700,
	PlantOverLimit = { "Bamboo", "Mushroom", "Rocket Pop" },
	ExpandLimit = 3,
	MaxPetSlots = 6,
	MailReceivers = { "BaconsNIonz95" },
	MailSendItems = {
		["Raccoon"] = { Amount = 1, To = { "mushroom15gold" } },
		["Bald Eagle"] = { Amount = 1, To = { "mushroom15gold" } },
		["Mega"] = "All",
		["Moon Bloom"] = "All",
		["Hypno Bloom"] = "All",
		["Dragon's Breath"] = "All",
		["Super Sprinkler"] = "All",
		["Super Watering Can"] = "All",
	},
	ShowUserWebhook = true,
	WebhookUrl = "https://discord.com/api/webhooks/1245486691553247293/HljlWDWOzLgz0LLUO4-Ar8_4bxpi07LTbMW9Fq7rnxlBENeQWpnG7F7nxEDu_8KfxakF",
	DiscordId = "",
	ServerSpread = true,
	UUID = "",
	RamKickLimit = 6000,
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/7f7baee1f0b7e01fe5ee8a3f5aabbfbf.lua"))()
